# Kaynak: 9903 sayılı Karar, RG 30.05.2025/32915, PDF s.21 (EK-2) ve s.43-50 (EK-5); görsel okuma 26.09.2026
EK2 = {
1: "Ankara Antalya Bursa Eskişehir İstanbul İzmir Kocaeli Muğla".split(),
2: "Aydın Balıkesir Bolu Çanakkale Denizli Edirne Kayseri Konya Manisa Mersin Sakarya Tekirdağ Yalova".split(),
3: "Adana Bilecik Burdur Düzce Gaziantep Isparta Karabük Karaman Kırıkkale Kırklareli Kütahya Nevşehir Rize Samsun Trabzon Uşak Zonguldak".split(),
4: "Afyonkarahisar Aksaray Amasya Artvin Çorum Elazığ Erzincan Kastamonu Kırşehir Malatya Sivas".split(),
5: "Bartın Bayburt Çankırı Erzurum Giresun Hatay Kahramanmaraş Kilis Niğde Ordu Osmaniye Sinop Tokat Tunceli Yozgat".split(),
6: "Adıyaman Ağrı Ardahan Batman Bingöl Bitlis Diyarbakır Gümüşhane Hakkâri Iğdır Kars Mardin Muş Siirt Şanlıurfa Şırnak Van".split(),
}
EK5 = {
"Adana":"Aladağ Feke İmamoğlu Karaisalı Karataş Pozantı Saimbeyli Tufanbeyli Yumurtalık",
"Afyonkarahisar":"Bayat Çobanlar Evciler Hocalar İhsaniye Kızılören Sinanpaşa",
"Aksaray":"Ağaçören Eskil Gülağaç Güzelyurt Sultanhanı",
"Amasya":"Göynücek Hamamözü",
"Ankara":"Bala Çamlıdere Evren Güdül Haymana Kalecik",
"Antalya":"Akseki Gündoğmuş İbradı",
"Aydın":"Bozdoğan Buharkent Germencik Karacasu Karpuzlu Koçarlı Köşk Kuyucak Sultanhisar Yenipazar",
"Balıkesir":"Balya Dursunbey Havran İvrindi Kepsut Manyas Savaştepe Sındırgı",
"Bilecik":"Gölpazarı İnhisar Pazaryeri Yenipazar",
"Bolu":"Dörtdivan Göynük Kıbrıscık Mengen Mudurnu Seben",
"Burdur":"Ağlasun Altınyayla Çavdır Çeltikçi Kemer Tefenni Yeşilova",
"Bursa":"Büyükorhan Harmancık Keles Orhaneli",
"Çanakkale":"Bayramiç Yenice",
"Çankırı":"Bayramören Yapraklı",
"Çorum":"Bayat Boğazkale Dodurga Kargı Laçin Mecitözü Oğuzlar Ortaköy Uğurludağ",
"Denizli":"Babadağ Baklan Bekilli Beyağaç Bozkurt Çal Çameli Çardak Güney Kale",
"Düzce":"Cumayeri Çilimli Gölyaka Yığılca",
"Edirne":"Enez Havsa İpsala Lalapaşa Meriç Süloğlu",
"Elazığ":"Ağın",
"Erzincan":"Çayırlı Kemah Otlukbeli Tercan Üzümlü",
"Erzurum":"Çat Hınıs Karaçoban Karayazı Köprüköy Şenkaya Tekman",
"Eskişehir":"Alpu Beylikova Çifteler Günyüzü Han Mahmudiye Mihalgazi Mihalıççık Sarıcakaya Seyitgazi",
"Gaziantep":"Karkamış Oğuzeli Yavuzeli",
"Giresun":"Çamoluk",
"Isparta":"Aksu Atabey Gelendost Senirkent Sütçüler Şarkikaraağaç Yenişarbademli",
"İzmir":"Bayındır Beydağ Kınık Kiraz",
"Karabük":"Eflani Eskipazar Ovacık Yenice",
"Karaman":"Ayrancı Başyayla Ermenek Sarıveliler",
"Kastamonu":"Ağlı Araç Cide Doğanyurt Küre Pınarbaşı Şenpazar",
"Kayseri":"Akkışla Bünyan Felahiye İncesu Özvatan Pınarbaşı Sarıoğlan Sarız Tomarza Yahyalı Yeşilhisar",
"Kırıkkale":"Balışeyh Çelebi Delice Karakeçili Keskin Sulakyurt",
"Kırklareli":"Demirköy Kofçaz Pehlivanköy",
"Kırşehir":"Akçakent Akpınar Boztepe Çiçekdağı",
"Kilis":"Elbeyli",
"Kocaeli":"Kandıra",
"Konya":"Ahırlı Akören Altınekin Bozkır Çeltik Çumra Derbent Derebucak Doğanhisar Emirgazi Güneysınır Hadim Halkapınar Hüyük Kadınhanı Sarayönü Taşkent Tuzlukçu Yalıhüyük Yunak",
"Kütahya":"Altıntaş Aslanapa Çavdarhisar Domaniç Dumlupınar Emet Hisarcık Pazarlar Şaphane",
"Manisa":"Ahmetli Demirci Gölmarmara Gördes Kırkağaç Köprübaşı Sarıgöl Saruhanlı Selendi",
"Mersin":"Aydıncık Bozyazı Çamlıyayla Gülnar Mut",
"Muğla":"Kavaklıdere Seydikemer",
"Nevşehir":"Acıgöl Derinkuyu Gülşehir Hacıbektaş",
"Niğde":"Altunhisar Çiftlik",
"Ordu":"Akkuş Çatalpınar Çaybaşı Gürgentepe İkizce Mesudiye",
"Osmaniye":"Sumbas",
"Rize":"Çamlıhemşin Derepazarı Güneysu Hemşin İkizdere İyidere Kalkandere",
"Sakarya":"Karapürçek Kaynarca Kocaali Taraklı",
"Samsun":"Alaçam Asarcık Ayvacık Kavak Ladik Salıpazarı Terme Vezirköprü Yakakent",
"Sinop":"Dikmen",
"Sivas":"Akıncılar Altınyayla Doğanşar Gölova Hafik İmranlı Koyulhisar Ulaş Yıldızeli",
"Tekirdağ":"Hayrabolu",
"Tokat":"Başçiftlik Sulusaray",
"Trabzon":"Araklı Çarşıbaşı Dernekpazarı Düzköy Hayrat Köprübaşı Şalpazarı Tonya",
"Uşak":"Banaz Karahallı Sivaslı Ulubey",
"Yozgat":"Aydıncık Kadışehri",
"Zonguldak":"Kilimli",
}
EK5 = {k: v.split() for k, v in EK5.items()}
